plugins {
    id 'java'
}

bootJar.enabled = false
jar.enabled = true

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':module-common')
    implementation project(':module-domain')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springdoc:springdoc-openapi-ui:1.6.6'
}

test {
    useJUnitPlatform()
}