plugins {
    id 'java'
}

group = 'com.slcube'
version = 'unspecified'

repositories {
    mavenCentral()
}

subprojects {
    dependencies {
        implementation project(':module-domain')
        implementation 'org.springframework.boot:spring-boot-starter-web'
        testImplementation platform('org.junit:junit-bom:5.10.0')
        testImplementation 'org.junit.jupiter:junit-jupiter'
    }
}


test {
    useJUnitPlatform()
}