pluginManagement {
	repositories {
		maven { url 'https://repo.spring.io/milestone' }
		maven { url 'https://repo.spring.io/snapshot' }
		gradlePluginPortal()
	}
}
rootProject.name = 'shelter_guide'
include 'module-common'
include 'module-batch'
include 'module-web'
include 'module-domain'
include 'module-infra'
include 'module-api'
include 'module-api:module-external-api'
findProject(':module-api:module-external-api')?.name = 'module-external-api'
include 'module-api:module-client-api'
findProject(':module-api:module-client-api')?.name = 'module-client-api'
include 'module-api:module-client-api'
findProject(':module-api:module-client-api')?.name = 'module-client-api'

