external-service:
  shelter-information:
    seoul:
      url: http://openapi.seoul.go.kr:8088/{apiKey}/json/LOCALDATA_114602/{startIndex}/{endIndex}
      api-key: ENC(jB8U4hlf2lE9t94u6SEwpW2nVsmZSxn1PJCoAfL6oDpAv3TBCW8GrQ==)
    gyeong-gi:
      url: https://openapi.gg.go.kr/CivilDefenseEvacuation?type=json&key={apiKey}?pIndex={pageIndex}&pSize={pSize}
      api-key: ENC(R8ZSvLIZwmyyLbPsyqBlarZ+pwaS2x/11zd9w0TBmw1BTTkci/fFJIjWKhCYGOjF)
    jeolla-buk-do:
      url: https://api.odcloud.kr/api/15055712/v1/uddi:2047b907-2c87-4177-8411-fb0e71043d2f_201708171411?page={pageIndex}&perPage={pageSize}&serviceKey={apiKey}
      api-key: ENC(Gs0f7dJh9s7d9VX7C2HPC41sUTHnISBGcLElxp3ymCKc1byWL1NYg9RzB4p4u6mE3DymtmzmqsINQWqtkYZlZTQipciEn6vladwdn7fLZqNXxXF0spDyGLUZyzJmX10mFtxw/SoqH29W4aSqHsn3GQ==)
    gyeong-sang-nam-do:
      url: https://api.odcloud.kr/api/3083902/v1/uddi:466f096f-f495-4917-b541-93f1037b82c1_201808191154?page={pageIndex}&perPage={pageSize}&serviceKey={apiKey}
      api-key: ENC(vle6sUQe+0+rZ4gEbICPTEapA24sNp/AdAvZHOr/kGkOEgGWU9+zQInYXae9aGfvpbLSSl5XIFRQ//+JpjzR67QQ2Ol69iACzlulCkDrqhIIkGjMgHk45Dsbc+LTsR0LRpa9B4l+vkKNGDs+EEnJ5g==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  batch:
    job:
      names: ${job.name:NONE}