external-service:
  shelter-information:
    seoul:
      url: http://openapi.seoul.go.kr:8088/{apiKey}/json/LOCALDATA_114602
      api-key: ENC(jB8U4hlf2lE9t94u6SEwpW2nVsmZSxn1PJCoAfL6oDpAv3TBCW8GrQ==)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  batch:
    job:
      names: "shelterInformationExternalApiJob"