plugins {
    id 'java'
}

group = 'com.slcube'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':module-domain')
    implementation 'org.springdoc:springdoc-openapi-ui:1.6.6'
    runtimeOnly project(':module-infra')
//    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}